name: fab-agon-emulator
base: core24
version: 0.9.99
summary: Fab Agon Emulator
description: |
  Agon Light, Agon Light 2, Agon Console8 Emulator for Linux, Windows, any system with libSDL

grade: stable
confinement: strict

compression: lzo

layout:
  /usr/lib/$CRAFT_ARCH_TRIPLET/alsa-lib:
    bind: $SNAP/usr/lib/$CRAFT_ARCH_TRIPLET/alsa-lib

parts:
  alsa-pulseaudio:
    plugin: dump
    source: .
    override-pull: |
      mkdir etc -p
      cat > etc/asound.conf <<EOF
      pcm.!default {
          type pulse
          fallback "sysdefault"
          hint {
              show on
              description "Default ALSA Output (currently PulseAudio Sound Server)"
          }
      }
      ctl.!default {
          type pulse
          fallback "sysdefault"
      }
      EOF
  launcher:
    plugin: dump
    source: snap/local
  agon-bas:
    plugin: dump
    after: [fab-agon-emulator]
    source: https://github.com/pngwen/agon-bas.git
    organize:
      "*.BAS": sdcard/agon-bas/
      "*.BBC": sdcard/agon-bas/
      README.MD: sdcard/agon-bas/
  pizza-dash:
    plugin: dump
    after: [fab-agon-emulator]
    source: https://github.com/NicholasPratt/Pizza-Dash.git
    organize:
      PIZZADASH.BAS: sdcard/Pizza-Dash/
      README.md: sdcard/Pizza-Dash/
  nova-star:
    plugin: dump
    after: [fab-agon-emulator]
    source: https://github.com/NicholasPratt/Nova-Star.git
    organize:
      NOVASTAR.BAS: sdcard/Nova-Star/
      LICENSE: sdcard/Nova-Star/
      README.md: sdcard/Nova-Star/
  examples:
    plugin: dump
    after: [fab-agon-emulator]
    source: https://github.com/TheByteAttic/AgonLight.git
    source-subdir: "uSD card files"
    organize:
      examples: sdcard/examples
      tests: sdcard/tests
      resources: sdcard/resources
    prime:
     - -bbcbasic.bin
     - -autoexec.txt
     - -README.md
  fab-agon-emulator:
    after: [alsa-pulseaudio]
    plugin: nil
    source: https://github.com/tomm/fab-agon-emulator.git
    source-tag: $SNAPCRAFT_PROJECT_VERSION
    stage-packages:
      - libsdl2-2.0-0
    build-packages:
      - libsdl2-dev
      - wget
    build-snaps:
      - rustup
    override-pull: |
      set -xeu
      craftctl default
      #git submodule update --init --recursive
    override-build: |
      set -xeu
      # Bodge to grab the firmware because the release came out without it
      wget "https://github.com/tomm/fab-agon-emulator/raw/refs/heads/main/firmware/mos_platform.bin" -O "$SNAPCRAFT_PART_SRC"/firmware/mos_platform.bin
      wget "https://github.com/tomm/fab-agon-emulator/raw/refs/heads/main/firmware/mos_platform.map" -O "$SNAPCRAFT_PART_SRC"/firmware/mos_platform.map
      /snap/bin/rustup default nightly
      cargobin=$HOME/.rustup/toolchains/$(rustup toolchain list | grep nightly | cut -d' ' -f1)/bin/cargo
      FORCE=1 $cargobin build -v -r
      make
      mkdir "$SNAPCRAFT_PART_INSTALL"/bin
      cp -a -v -r target/release/fab-agon-emulator "$SNAPCRAFT_PART_INSTALL"/bin
      cp -a -v -r "$SNAPCRAFT_PART_SRC"/firmware "$SNAPCRAFT_PART_INSTALL"
      cp -a -v -r "$SNAPCRAFT_PART_SRC"/sdcard "$SNAPCRAFT_PART_INSTALL"
    prime:
      - -usr/lib/x86_64-linux-gnu/libpulse-simple.so.0.1.1

apps:
  fab-agon-emulator:
    extensions: [ gnome ]
    command: bin/launch
    environment:
      ALSA_CONFIG_PATH: "$SNAP/etc/asound.conf"
    plugs:
      - joystick
      - audio-playback
      - audio-record
      - alsa
      - network
      - network-bind
      - home
      - removable-media
