name: fab-agon-emulator
base: core22
adopt-info: fab-agon-emulator
summary: Fab Agon Emulator
description: |
  Agon Light, Agon Light 2, Agon Console8 Emulator for Linux, Windows, any system with libSDL

grade: stable
confinement: strict

compression: lzo

architectures:
  - build-on: amd64
  - build-on: arm64
  - build-on: armhf

layout:
  /usr/lib/$CRAFT_ARCH_TRIPLET/alsa-lib:
    bind: $SNAP/usr/lib/$CRAFT_ARCH_TRIPLET/alsa-lib

parts:
  alsa-pulseaudio:
    plugin: dump
    source: .
    override-pull: |
      mkdir etc -p
      cat > etc/asound.conf <<EOF
      pcm.!default {
          type pulse
          fallback "sysdefault"
          hint {
              show on
              description "Default ALSA Output (currently PulseAudio Sound Server)"
          }
      }
      ctl.!default {
          type pulse
          fallback "sysdefault"
      }
      EOF
  launcher:
    plugin: dump
    source: snap/local
  fab-agon-emulator:
    after: [alsa-pulseaudio]
    plugin: rust
    source: https://github.com/tomm/fab-agon-emulator.git
    stage-packages:
      - libsdl2-2.0-0
    build-packages:
      - cargo
      - libsdl2-dev
    override-pull: |
      craftctl default
      last_committed_tag="$(git describe --tags --abbrev=0)"
      echo $last_committed_tag
      last_released_tag="$(snap info $SNAPCRAFT_PROJECT_NAME | awk '$1 == "latest/beta:" { print $2 }')"
      echo $last_released_tag
      # If the latest tag from the upstream project has not been released to
      # beta, build that tag instead of master.
      if [ "${last_committed_tag}" != "${last_released_tag}" ]; then
        git fetch
        git checkout "${last_committed_tag}"
        echo "Setting version to $last_committed_tag"
        craftctl set version="${last_committed_tag}"
      else
        echo "Setting version to $(git rev-parse --short HEAD)"
        craftctl set version="$(git rev-parse --short HEAD)"
      fi
    override-build: |
      set -xeu
      cargo build -v -r
      mkdir "$SNAPCRAFT_PART_INSTALL"/bin
      cp -a -r target/release/fab-agon-emulator "$SNAPCRAFT_PART_INSTALL"/bin
      cp -a -r firmware "$SNAPCRAFT_PART_INSTALL"
      cp -a -r "$SNAPCRAFT_PART_SRC"/sdcard "$SNAPCRAFT_PART_INSTALL"

apps:
  fab-agon-emulator:
    extensions: [ gnome ]
    command: bin/launch
    environment:
      ALSA_CONFIG_PATH: "$SNAP/etc/asound.conf"
    plugs:
      - joystick
      - audio-playback
      - audio-record
      - alsa
      - network
      - network-bind
      - home
      - removable-media